workflows:
  ios-testflight:
    name: iOS TestFlight Release
    max_build_duration: 90
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: ChiraagEAzaa
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mirali.chiraageazaa
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_APPLE_ID: 6786198976
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false